name: rss-Bot

on:
  schedule:
    - cron: "0 23,4,10 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          DISCORD_WEBHOOK_AI: ${{ secrets.DISCORD_WEBHOOK_AI }}
          DISCORD_WEBHOOK_TECH: ${{ secrets.DISCORD_WEBHOOK_TECH }}
          DISCORD_WEBHOOK_REDDIT: ${{ secrets.DISCORD_WEBHOOK_REDDIT }}
           DISCORD_WEBHOOK_IDEA: ${{ secrets.DISCORD_WEBHOOK_IDEA }}
